title: Kevin Marsh
email: kevin.marsh@gmail.com
description: >
  Blog of Kevin Marsh, a web developer from Toledo, Ohio. Co-founder of Vintage
  Aerial and Founder of variart. Perhaps best known as the creator of SongMeanings.
keywords: >
  Kevin Marsh, Toledo, web design, willcodeforfoo, dotfiles.org, lifemetric,
  SongMeanings, web developer, xhtml, Rails, Ruby on Rails, vintage aerial,
  sfc, digital imaging, photography
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevinmarsh.com"
twitter_username: willcodeforfoo
github_username: willcodeforfoo
permalink: /:year/:month/:day/:title.html
lsi: true

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions:
    - autolink
    - footnotes
    - tables
    - smart

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
