baseURL: https://kevinmarsh.com
disablePathToLower: true
languageCode: en-us
title: Kevin Marsh
permalinks:
  posts: /:year/:month/:day/:slug/
markup:
  highlight:
    noClasses: false
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: feed

security:
  exec:
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
      - ^ASDF_DIR$
      - ^HOME$
